### PR TITLE
Update docs on requirement that machine key be from a root account

### PR DESCRIPTION
**Pull request by justincjohnson**
Doc updates, inspired by a recent support issue.  Hopefully my understanding of the issue and terminology is correct.

### CODE REVIEW

**Comment by justincjohnson** [comment]
@expede reword to your hearts content.

My thought is that long term we want this to not be an issue such that no doc is necessary.  In the meantime, attempt to gently guide people into the "pit of success" as well as help them know what to do if they have issues.

It seems like some slight tweaks should be made to the Fission Guide as well.

**Comment by expede** [comment]
@justincjohnson we can add this for now, but it actually doesn't need to be from the root machine. There is a bug where the root can't be from a browser, due to library inconsistencies. This problem will go away as part of our work upgrading UCAN

**Review by expede — APPROVED** [review]
LGTM!

Can you also open a tracking issue for us to remove this text when we've fixed the underlying bug? Thanks!

**Comment by justincjohnson** [comment]
Thanks for the clarification!  I corrected the wording and created https://github.com/fission-suite/publish-action/issues/19 to track the README updates.

**Pull request merged**
